# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.18.4
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.35
maven_group=fr.madu59
archives_base_name=ptp

# Dependencies
fabric_version=0.155.2+26.1.2
modmenu_version = 20.0.1

modrinth_id = preyrsIh
curseforge_id = 1348218